PREFIX ex: <http://example.org/vocabulary/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbo: <http://dbpedia.org/resource/classes#>

# Select 3 occupants of the town hall of Svätý Jur that live there living there longest

SELECT ?name ?date
WHERE {
    ?town a dbo:Town;
        ex:townName ?tn.
    
    ?occ a ex:Occupant;
        foaf:firstName ?name;
        ex:dateFrom ?date.

    ?town ex:townHall ?building.
    ?occ ex:livesIn ?building.
FILTER (STR(?tn) = "Svätý Jur")
} 
ORDER BY ?date
LIMIT 3
