@startuml townDiagram

hide circle

object Towns {
  <#lightblue,#black>|= Id |= townNameCS |= townNameSK |= townNameEN  |=  hasFlag  |= hasBroadcast |= mayorId |= termStart |= termEnd |
  <#white>| int | string - cs lang | string - sk lang | string - en lang | boolean | boolean | int | date | date |
  <#white>| primary key \n - required | | | | required | required | foreign key to \n People - required | required | required |
}

' TODO: do we want to have firstNameCS, firstNameEN etc.
' If not which lang will we choose for the RDF
object People {
  ' TODO: Is ok to represent middleNames as one string 
  <#lightblue,#black>|= Id |= firstName |= surname |= middleNames |
  <#white>| int | string | string | string |
  <#white>| primary key \n - required | required | required | |
}

object Occupants {
  <#lightblue,#black>|= Id |= personId |= HouseId |= dateFrom |= unpaidFees |
  <#white>| int | int | int | date | boolean |
  <#white>| primary key \n - required | foreign key to \n People - required | foreign key to \n Houses - required | required | required |
}

object TownHallMap {
  <#lightblue,#black>|= townId |= houseId |
  <#white>| int | int |
  <#white>| primary key to \n Towns - required | primary key to \n Houses - required | date \n - required | boolean \n - required |
}

' TODO: the same problem with streetName and langs
object Streets {
  <#lightblue,#black>|= Id |= townId |= streetName |= hasSidewalk |
  <#white>| int | int | string | boolean |
  <#white>| primary key \n - required | foreign key to \n Towns - required | required | required |
}

object Houses {
  <#lightblue,#black>|= Id |= streetId |= houseNumber |= colourHexCode |= area |
  <#white>| int | int | int | string | decimal |
  <#white>| primary key \n - required | foreign key to \n Streets - required | required |  required | required |
}

Occupants -> Houses : "Foreign key"
Occupants -d-> People : "Foreign key"
Houses -d-> Streets : "Foreign key"
Streets -> Towns : "Foreign key"
Towns -d-> People : "Foreign key"
TownHallMap -d-> Towns : "Foreign key"
TownHallMap -d-> Houses : "Foreign key"





@enduml