PREFIX ex: <http://example.org/vocabulary/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dbo: <http://dbpedia.org/resource/classes#>


# get town where michal lives

SELECT ?town
WHERE{
    ?occupant a ex:Occupant;
        ex:lives_in ?house;
        foaf:name "Michal"@cs.
    ?house ex:situatedOn ?street.
    ?street ex:locatedIn ?town.  
}