PREFIX ex: <http://example.org/vocabulary/>
PREFIX dbo: <http://dbpedia.org/resource/classes#>

# select mayors and their addresses  

SELECT ?mayor ?townName ?streetName ?houseNumber
WHERE {
  ?mayor a ex:Mayor ;
    ex:livesIn ?house .

  ?house ex:houseNumber ?houseNumber .
  ?house ex:situatedOn ?street .
  
  ?street ex:streetName ?streetName .
  ?street ex:locatedIn ?town .

  ?town ex:townName ?townName .
}
