@startuml MayorDiagram

hide circle


class "Town" as Town {
  --
  townName
  hasFlag
  hasBroadcast
}


class "House" as House{
  --
  number
  colour
  area
}


Town "0..1" <-l- "1..1" House : "                 "


@enduml